SELECT
	OWNER,
	OBJECT_NAME,
	PROCEDURE_NAME,
	OBJECT_TYPE,
	SUBPROGRAM_ID,
	OVERLOAD
FROM
	ALL_PROCEDURES
WHERE
	((OBJECT_TYPE = 'PACKAGE'
	AND PROCEDURE_NAME IS NOT NULL)
	OR OBJECT_TYPE != 'PACKAGE')
	AND OWNER IN (:owners)
ORDER BY
	OBJECT_TYPE DESC,
	OBJECT_NAME,
	SUBPROGRAM_ID