ALTER SESSION SET CONTAINER=XEPDB1;

CREATE USER OO4J IDENTIFIED BY OO4J;
GRANT CREATE SESSION TO OO4J;
GRANT CREATE TABLE TO OO4J;
GRANT CREATE VIEW TO OO4J;
GRANT CREATE ANY TRIGGER TO OO4J;
GRANT CREATE ANY PROCEDURE TO OO4J;
GRANT CREATE SEQUENCE TO OO4J;
GRANT CREATE SYNONYM TO OO4J;
